import type { ReplicatePointCloudSample } from './types';

const ASSET_ROOT = 'core-img/replicate-3d';
const TEST_1 = `${ASSET_ROOT}/test-1-standard.jpg`;
const TEST_2 = `${ASSET_ROOT}/test-2-standard.jpg`;
const UNDER_ONE_CENT = 'Less than US$0.01';

/**
 * Results captured manually from Replicate on 2026-09-09.
 *
 * Binary outputs are bundled with the PoC so the comparison remains usable after Replicate's
 * delivery links expire. Beam Studio only reads these fixtures; it never creates a prediction.
 */
export const REPLICATE_CAPTURED_TEST_SAMPLES = [
  {
    approximateCostUsd: 0.01,
    availability: 'preview-only',
    commercialUse: true,
    disabledReason:
      'Both thundercloud attempts failed while exporting mesh.glb: zero-size array to reduction operation maximum. Original: queue 3m 36.4s, run 15.2s. Standard: queue 27.5s, run 2.9s.',
    displays: [],
    format: 'ply',
    group: 'captured-test',
    id: 'moge-2-test-1-failed',
    inputPreview: { kind: 'image', url: TEST_1 },
    label: 'MoGe-2 - Test 1 (Thundercloud, failed)',
    license: 'MIT',
    model: 'jasonod888/moge2',
    modelUrl: 'https://replicate.com/jasonod888/moge2',
    outputUrl: TEST_1,
    resultNote: 'Changing from the original 6000×4000 image to 1024×682 did not resolve the empty mesh output.',
    runMetrics: { cost: 'Cost not recorded' },
    source: { kind: 'image', url: TEST_1 },
    version: 'daa7a9329b3d6bb513f3a20def9451b6e3cf234afe2bb60ba38f96ecd33c81f7',
  },
  {
    approximateCostUsd: 0.01,
    availability: 'importable',
    commercialUse: true,
    displayOutputs: {
      'reference-mesh': { format: 'glb-mesh', url: `${ASSET_ROOT}/moge2-test-2-mesh.glb` },
    },
    displays: ['point-cloud', 'reference-mesh'],
    format: 'ply',
    group: 'captured-test',
    id: 'moge-2-test-2',
    inputPreview: { kind: 'image', url: TEST_2 },
    label: 'MoGe-2 - Test 2 (Flower)',
    license: 'MIT',
    model: 'jasonod888/moge2',
    modelUrl: 'https://replicate.com/jasonod888/moge2',
    outputUrl: `${ASSET_ROOT}/moge2-test-2-pointcloud.ply`,
    resultPreview: { kind: 'image', label: 'Depth', url: `${ASSET_ROOT}/moge2-test-2-preview.png` },
    runMetrics: { cost: UNDER_ONE_CENT, running: '3.2s' },
    source: { kind: 'image', url: TEST_2 },
    version: 'daa7a9329b3d6bb513f3a20def9451b6e3cf234afe2bb60ba38f96ecd33c81f7',
  },
  {
    approximateCostUsd: 0.01,
    availability: 'importable',
    commercialUse: true,
    displayOutputs: {
      'reference-mesh': { format: 'glb-mesh', url: `${ASSET_ROOT}/map-anything-test-1-mesh.glb` },
    },
    displays: ['point-cloud', 'reference-mesh'],
    format: 'glb',
    group: 'captured-test',
    id: 'map-anything-test-1',
    inputPreview: { kind: 'image', url: TEST_1 },
    label: 'MapAnything - Test 1 (Thundercloud)',
    license: 'Apache-2.0',
    model: 'vufinder/map-anything',
    modelUrl: 'https://replicate.com/vufinder/map-anything',
    outputUrl: `${ASSET_ROOT}/map-anything-test-1-point-cloud.glb`,
    resultNote: '45,870 points; the mesh contains 45,639 surface vertices and 86,284 triangles.',
    runMetrics: { cost: UNDER_ONE_CENT, queued: '1m 41.4s', running: '1.1s', total: '1m 42.6s' },
    source: { kind: 'image', url: TEST_1 },
    version: 'bb68c254a65d3ce6b173909181d2dfbd044300b3ebca25ab63f07aa7eb1eebff',
  },
  {
    approximateCostUsd: 0.01,
    availability: 'importable',
    commercialUse: true,
    displayOutputs: {
      'reference-mesh': { format: 'glb-mesh', url: `${ASSET_ROOT}/map-anything-test-2-mesh.glb` },
    },
    displays: ['point-cloud', 'reference-mesh'],
    format: 'glb',
    group: 'captured-test',
    id: 'map-anything-test-2',
    inputPreview: { kind: 'image', url: TEST_2 },
    label: 'MapAnything - Test 2 (Flower)',
    license: 'Apache-2.0',
    model: 'vufinder/map-anything',
    modelUrl: 'https://replicate.com/vufinder/map-anything',
    outputUrl: `${ASSET_ROOT}/map-anything-test-2-point-cloud.glb`,
    resultNote: '57,959 points. The portrait input was padded to 518×518 by the model.',
    runMetrics: { cost: UNDER_ONE_CENT, queued: '25.6s', running: '1.8s', total: '27.5s' },
    source: { kind: 'image', url: TEST_2 },
    version: 'bb68c254a65d3ce6b173909181d2dfbd044300b3ebca25ab63f07aa7eb1eebff',
  },
  {
    approximateCostUsd: 0.01,
    availability: 'importable',
    commercialUse: true,
    conversionOptions: { focalLengthPx: 1298.7489013671875, invertDepth: true, reliefDepthRatio: 0.22 },
    displays: ['point-cloud'],
    format: 'depth-pro-npz',
    group: 'captured-test',
    id: 'depth-pro-test-1',
    inputPreview: { kind: 'image', url: TEST_1 },
    label: 'Depth Pro - Test 1 (Thundercloud)',
    license: 'Apple Sample Code License',
    model: 'ibrahimpenekli/depth-pro',
    modelUrl: 'https://replicate.com/ibrahimpenekli/depth-pro',
    outputUrl: `${ASSET_ROOT}/depth-pro-test-1.npz`,
    resultNote:
      'Poor result: 99.823% of pixels equal the maximum depth (10,000), leaving almost no usable variation or relief range.',
    resultPreview: { kind: 'image', label: 'Depth', url: `${ASSET_ROOT}/depth-pro-test-1-preview.jpg` },
    runMetrics: { cost: UNDER_ONE_CENT, queued: '11ms', running: '1.2s', total: '1.2s' },
    source: { kind: 'image', url: TEST_1 },
    version: '8bee17f621ab23567c836703be980b3aa1552127b252b7ef9f6ce6db6c4619ef',
  },
  {
    approximateCostUsd: 0.01,
    availability: 'importable',
    commercialUse: true,
    conversionOptions: { focalLengthPx: 2634.184814453125, invertDepth: true, reliefDepthRatio: 0.22 },
    displays: ['point-cloud', 'relief-mesh'],
    format: 'depth-pro-npz',
    group: 'captured-test',
    id: 'depth-pro-test-2',
    inputPreview: { kind: 'image', url: TEST_2 },
    label: 'Depth Pro - Test 2 (Flower)',
    license: 'Apple Sample Code License',
    model: 'ibrahimpenekli/depth-pro',
    modelUrl: 'https://replicate.com/ibrahimpenekli/depth-pro',
    outputUrl: `${ASSET_ROOT}/depth-pro-test-2.npz`,
    resultNote: 'Usable metric depth from 0.88m to 2.72m with clear foreground/background separation.',
    resultPreview: { kind: 'image', label: 'Depth', url: `${ASSET_ROOT}/depth-pro-test-2-preview.jpg` },
    runMetrics: { cost: UNDER_ONE_CENT, queued: '12ms', running: '1s', total: '1s' },
    source: { kind: 'image', url: TEST_2 },
    version: '8bee17f621ab23567c836703be980b3aa1552127b252b7ef9f6ce6db6c4619ef',
  },
  {
    approximateCostUsd: 0.01,
    availability: 'preview-only',
    commercialUse: 'review',
    disabledReason: 'This Replicate version returned only colourised previews and no raw float depth.',
    displays: ['relief-mesh'],
    format: 'normal-map-preview',
    group: 'captured-test',
    id: 'metric3dv2-test-1',
    inputPreview: { kind: 'image', url: TEST_1 },
    label: 'Metric3D V2 - Test 1 (Thundercloud)',
    license: 'Commercial terms require review',
    model: 'visionaix/metric3dv2',
    modelUrl: 'https://replicate.com/visionaix/metric3dv2',
    outputUrl: `${ASSET_ROOT}/metric3dv2-test-1-preview.png`,
    resultNote: 'Median depth hit the configured 200m limit, so the result has little useful depth variation.',
    resultPreview: { kind: 'image', label: 'Composite', url: `${ASSET_ROOT}/metric3dv2-test-1-preview.png` },
    runMetrics: { cost: UNDER_ONE_CENT, queued: '1m 31.8s', running: '3.1s', total: '1m 34.9s' },
    source: { kind: 'image', url: TEST_1 },
    version: 'bbf71abe79f8a95fce080dc07f1cb6bcd215b3a237631fdb7189661d3738e883',
  },
  {
    approximateCostUsd: 0.01,
    availability: 'preview-only',
    commercialUse: 'review',
    disabledReason: 'This Replicate version returned only colourised previews and no raw float depth.',
    displays: ['relief-mesh'],
    format: 'normal-map-preview',
    group: 'captured-test',
    id: 'metric3dv2-test-2',
    inputPreview: { kind: 'image', url: TEST_2 },
    label: 'Metric3D V2 - Test 2 (Flower)',
    license: 'Commercial terms require review',
    model: 'visionaix/metric3dv2',
    modelUrl: 'https://replicate.com/visionaix/metric3dv2',
    outputUrl: `${ASSET_ROOT}/metric3dv2-test-2-preview.png`,
    resultNote: 'Normals are readable, but max_depth=200m makes the close-up colourised depth preview nearly uniform.',
    resultPreview: { kind: 'image', label: 'Composite', url: `${ASSET_ROOT}/metric3dv2-test-2-preview.png` },
    runMetrics: { cost: UNDER_ONE_CENT, queued: '2m 49s', running: '2.7s', total: '2m 51.8s' },
    source: { kind: 'image', url: TEST_2 },
    version: 'bbf71abe79f8a95fce080dc07f1cb6bcd215b3a237631fdb7189661d3738e883',
  },
  {
    approximateCostUsd: 0.01,
    availability: 'importable',
    commercialUse: true,
    conversionOptions: { reliefDepthRatio: 0.22 },
    displays: ['point-cloud', 'relief-mesh'],
    format: 'depth-image',
    group: 'captured-test',
    id: 'zoedepth-test-1',
    inputPreview: { kind: 'image', url: TEST_1 },
    label: 'ZoeDepth - Test 1 (Thundercloud)',
    license: 'MIT',
    model: 'cjwbw/zoedepth',
    modelUrl: 'https://replicate.com/cjwbw/zoedepth',
    outputUrl: `${ASSET_ROOT}/zoedepth-test-1.png`,
    resultPreview: { kind: 'image', label: 'Depth', url: `${ASSET_ROOT}/zoedepth-test-1.png` },
    runMetrics: { cost: UNDER_ONE_CENT, queued: '5m 34s', running: '5.8s', total: '5m 39.8s' },
    source: { kind: 'image', url: TEST_1 },
    version: '6375723d97400d3ac7b88e3022b738bf6f433ae165c4a2acd1955eaa6b8fcb62',
  },
  {
    approximateCostUsd: 0.01,
    availability: 'importable',
    commercialUse: true,
    conversionOptions: { reliefDepthRatio: 0.22 },
    displays: ['point-cloud', 'relief-mesh'],
    format: 'depth-image',
    group: 'captured-test',
    id: 'zoedepth-test-2',
    inputPreview: { kind: 'image', url: TEST_2 },
    label: 'ZoeDepth - Test 2 (Flower)',
    license: 'MIT',
    model: 'cjwbw/zoedepth',
    modelUrl: 'https://replicate.com/cjwbw/zoedepth',
    outputUrl: `${ASSET_ROOT}/zoedepth-test-2.png`,
    resultNote: 'Visible horizontal bands, background glow and compressed petal detail.',
    resultPreview: { kind: 'image', label: 'Depth', url: `${ASSET_ROOT}/zoedepth-test-2.png` },
    runMetrics: { cost: UNDER_ONE_CENT, queued: '3m 59.1s', running: '15.8s', total: '4m 15s' },
    source: { kind: 'image', url: TEST_2 },
    version: '6375723d97400d3ac7b88e3022b738bf6f433ae165c4a2acd1955eaa6b8fcb62',
  },
  {
    approximateCostUsd: 0.01,
    availability: 'importable',
    commercialUse: true,
    conversionOptions: { reliefDepthRatio: 0.22 },
    displays: ['point-cloud', 'relief-mesh'],
    format: 'depth-image',
    group: 'captured-test',
    id: 'depth-anything-v2-test-1',
    inputPreview: { kind: 'image', url: TEST_1 },
    label: 'Depth Anything V2 Small - Test 1 (Thundercloud)',
    license: 'Apache-2.0 (Small)',
    model: 'chenxwh/depth-anything-v2',
    modelUrl: 'https://replicate.com/chenxwh/depth-anything-v2',
    outputUrl: `${ASSET_ROOT}/depth-anything-v2-test-1.png`,
    resultNote: 'The clearest thundercloud relative-depth result so far, with sharp boundaries and distinct layers.',
    resultPreview: { kind: 'image', label: 'Depth', url: `${ASSET_ROOT}/depth-anything-v2-test-1.png` },
    runMetrics: { cost: UNDER_ONE_CENT, queued: '14ms', running: '620ms', total: '634ms' },
    source: { kind: 'image', url: TEST_1 },
    version: 'b239ea33cff32bb7abb5db39ffe9a09c14cbc2894331d1ef66fe096eed88ebd4',
  },
  {
    approximateCostUsd: 0.01,
    availability: 'importable',
    commercialUse: true,
    conversionOptions: { reliefDepthRatio: 0.22 },
    displays: ['point-cloud', 'relief-mesh'],
    format: 'depth-image',
    group: 'captured-test',
    id: 'depth-anything-v2-test-2',
    inputPreview: { kind: 'image', url: TEST_2 },
    label: 'Depth Anything V2 Small - Test 2 (Flower)',
    license: 'Apache-2.0 (Small)',
    model: 'chenxwh/depth-anything-v2',
    modelUrl: 'https://replicate.com/chenxwh/depth-anything-v2',
    outputUrl: `${ASSET_ROOT}/depth-anything-v2-test-2.png`,
    resultNote: 'Good petal, stamen and stem separation; the dark background still becomes a smooth depth gradient.',
    resultPreview: { kind: 'image', label: 'Depth', url: `${ASSET_ROOT}/depth-anything-v2-test-2.png` },
    runMetrics: { cost: 'Cost not recorded', queued: '12ms', running: '660ms', total: '673ms' },
    source: { kind: 'image', url: TEST_2 },
    version: 'b239ea33cff32bb7abb5db39ffe9a09c14cbc2894331d1ef66fe096eed88ebd4',
  },
  {
    approximateCostUsd: 0.01,
    availability: 'importable',
    commercialUse: true,
    conversionOptions: { reliefDepthRatio: 0.22 },
    displays: ['point-cloud', 'relief-mesh'],
    format: 'depth-image',
    group: 'captured-test',
    id: 'midas-test-1',
    inputPreview: { kind: 'image', url: TEST_1 },
    label: 'MiDaS - Test 1 (Thundercloud)',
    license: 'MIT',
    model: 'cjwbw/midas',
    modelUrl: 'https://replicate.com/cjwbw/midas',
    outputUrl: `${ASSET_ROOT}/midas-test-1.png`,
    resultNote: 'Smooth broad gradients, but much less internal cloud detail than Depth Anything V2 Small.',
    resultPreview: { kind: 'image', label: 'Depth', url: `${ASSET_ROOT}/midas-test-1.png` },
    runMetrics: { cost: UNDER_ONE_CENT, queued: '24ms', running: '2.9s', total: '2.9s' },
    source: { kind: 'image', url: TEST_1 },
    version: 'a6ba5798f04f80d3b314de0f0a62277f21ab3503c60c84d4817de83c5edfdae0',
  },
  {
    approximateCostUsd: 0.01,
    availability: 'importable',
    commercialUse: true,
    conversionOptions: { reliefDepthRatio: 0.22 },
    displays: ['point-cloud', 'relief-mesh'],
    format: 'depth-image',
    group: 'captured-test',
    id: 'midas-test-2',
    inputPreview: { kind: 'image', url: TEST_2 },
    label: 'MiDaS - Test 2 (Flower)',
    license: 'MIT',
    model: 'cjwbw/midas',
    modelUrl: 'https://replicate.com/cjwbw/midas',
    outputUrl: `${ASSET_ROOT}/midas-test-2.png`,
    resultNote: 'Smooth flower relief with a minor halo and vertical smear near the left flower.',
    resultPreview: { kind: 'image', label: 'Depth', url: `${ASSET_ROOT}/midas-test-2.png` },
    runMetrics: { cost: UNDER_ONE_CENT, queued: '23ms', running: '2.7s', total: '2.8s' },
    source: { kind: 'image', url: TEST_2 },
    version: 'a6ba5798f04f80d3b314de0f0a62277f21ab3503c60c84d4817de83c5edfdae0',
  },
] as const satisfies ReadonlyArray<ReplicatePointCloudSample>;
