export default {
  BACKEND_DOWN: 'BACKEND_DOWN',
  BACKEND_UP: 'BACKEND_UP',

  CHECK_BACKEND_STATUS: 'CHECK_BACKEND_STATUS',
  CHECK_FOR_UPDATE: 'CHECK_FOR_UPDATE',
  CHECK_IP_EXIST: 'CHECK_IP_EXIST',
  CHECK_IP_EXIST_RESULT: 'CHECK_IP_EXIST_RESULT',
  DISABLE_MENU_ITEM: 'DISABLE_MENU_ITEM',

  DOWNLOAD_PROGRESS: 'DOWNLOAD_PROGRESS',
  DOWNLOAD_UPDATE: 'DOWNLOAD_UPDATE',
  ENABLE_MENU_ITEM: 'ENABLE_MENU_ITEM',
  FIND_FONT: 'FIND_FONT',

  FIND_FONTS: 'FIND_FONTS',

  FRONTEND_READY: 'FRONTEND_READY',

  GET_AVAILABLE_FONTS: 'GET_AVAILABLE_FONTS',
  MENU_CLICK: 'MENU_CLICK',
  NOTIFY_BACKEND_STATUS: 'NOTIFY_BACKEND_STATUS',
  NOTIFY_LANGUAGE: 'NOTIFY_LANGUAGE',

  NOTIFY_MACHINE_STATUS: 'NOTIFY_MACHINE_STATUS',

  POPUP_MENU: 'POPUP_MENU_ITEM',
  QUIT_AND_INSTALL: 'QUIT_AND_INSTALL',
  SET_AS_DEFAULT: 'SET_AS_DEFAULT',
  SET_EDITING_STANDARD_INPUT: 'SET_EDITING_STANDARD_INPUT',
  SUBSTITUTE_FONT: 'SUBSTITUTE_FONT',

  SVG_URL_TO_IMG_URL: 'SVG_URL_TO_IMG_URL',
  SVG_URL_TO_IMG_URL_DONE: 'SVG_URL_TO_IMG_URL_DONE',
  TEST_NETWORK: 'TEST_NETWORK',
  TEST_NETWORK_PROGRESS: 'TEST_NETWORK_PROGRESS',
  TEST_NETWORK_RESULT: 'TEST_NETWORK_RESULT',
  UPDATE_ACCOUNT: 'UPDATE_ACCOUNT',

  UPDATE_AVAILABLE: 'UPDATE_AVAILABLE',
  UPDATE_CUSTOM_TITLEBAR: 'UPDATE_CUSTOM_TITLEBAR',
  UPDATE_DOWNLOADED: 'UPDATE_DOWNLOADED',
};
