export default {
    CHANGE_MODE: 'flux-stduio/monitor/CHANGE_MODE',
    CHANGE_PATH: 'flux-studio/monitor/CHANGE_PATH',
    UPDATE_FOLDER_CONTENT: 'flux-studio/monitor/UPDATE_FOLDER_CONTENT',
    PREVIEW_FILE: 'flux-studio/monitor/PREVIEW_FILE',
    SELECT_ITEM: 'flux-studio/monitor/SELECT_ITEM',
    SET_DOWNLOAD_PROGRESS: 'flux-studio/monitor/SET_DOWNLOAD_PROGRESS',
    SET_UPLOAD_PROGRESS: 'flux-studio/monitor/SET_UPLOAD_PROGRESS',
    SHOW_WAIT: 'flux-studio/monitor/SHOW_WAIT',
    CLOSE_WAIT: 'flux-studio/monitor/CLOSE_WAIT',
    SET_CAMERA_OFFSET: 'beam-studio/monitor/SET_CAMERA_OFFSET',
    SET_MAINTAIN_MOVING: 'beam-studio/monitor/SET_MAINTAIN_MOVING',
    SET_CURRENT_POSITION: 'beam-studio/monitor/SET_CURRENT_POSITION',
    SET_RELOCATE_ORIGIN: 'beam-studio/monitor/SET_RELOCATE_ORIGIN',
};
