export default {
    UPDATE_LASER_PANEL: 'UPDATE_LASER_PANEL',
    BACK_TO_PREVIEW: 'BACK_TO_PREVIEW',
    SHOW_CROPPER: 'SHOW_CROPPER',
    END_IMAGE_TRACE: 'END_IMAGE_TRACE',
    START_DRAWING_PREVIEW_BLOB: 'START_DRAWING_PREVIEW_BLOB',
    END_DRAWING_PREVIEW_BLOB: 'END_DRAWING_PREVIEW_BLOB',
    CLEAR_CAMERA_CANVAS: 'CLEAR_CAMERA_CANVAS',
    RESET_PREVIEW_BUTTON: 'RESET_PREVIEW_BUTTON',
    SHOW_NETWORK_TESTING_PANEL: 'SHOW_NETWORK_TESTING_PANEL',
    SHOW_TASK_INTERPRETER: 'SHOW_TASK_INTERPRETER',
    SHOW_LAYER_COLOR_CONFIG: 'SHOW_LAYER_COLOR_CONFIG',
    DRAW_GUIDE_LINES: 'DRAW_GUIDE_LINES',
};
