import { todo } from '@core/helpers/is-dev';

/**
 * A 3D canvas object is represented by its geometry plus an SVG projection, and they must not be
 * conflated:
 *
 * 1. the **3D object** — a mesh, photo plane, or point cloud plus its 3D transform and engraving
 *    parameters. This is the source of truth and is what the three.js canvas renders.
 * 2. the **SVG projection** — a `<rect>` for meshes/point clouds or the editable `<image>` for a
 *    photo. Its geometry is the XY projection of the 3D object's bounding box. It exists so that selection, layer
 *    membership, undo/redo, clipboard and .beam serialization all reuse the existing svgedit
 *    plumbing, and so that anything reading a 2D bbox (alignment, framing,
 *    `getVisibleElementsAndBBoxes`) keeps working unchanged.
 *
 * The projection is **derived**: every change to the 3D transform recomputes its x/y/width/height. It is
 * never editable geometry on its own — a 2D edit (e.g. the XY inputs in DimensionPanel) has to be
 * routed back to the 3D object, which then re-projects.
 *
 * The two are linked by element id. For binary geometry, the id is also the key used by the .beam
 * file and the `stlObjects`/`pointCloudObjects` payload sent to Swiftray. A photo keeps its pixels
 * directly in the SVG image.
 */
todo(
  'TBC：註解裡，a 2D edit (e.g. the XY inputs in DimensionPanel) has to be routed back to the 3D object, which then re-projects. 實際上，在內雕模式裡，rect 不應該被接觸到，DimensionPanel 裡的值應該直接影響到 3D object，然後投影',
);
/**
 * Attributes on a 3D object's SVG projection. Everything Swiftray needs to place the geometry
 * travels on these because the projection ends up in both the exported SVG and the .beam file.
 */
export const STL_ATTR = {
  /**
   * Note: infill has no attribute of its own. It is the projection rect's **own `fill`**, set by the
   * same `InFillBlock` every 2D shape uses — a filled rect means "engrave the interior too".
   */
  /** Backend geometry: absent means STL mesh; `photo` uses image pixels; `point-cloud` selects BSPC. */
  kind: 'data-stl-kind',
  /** Slice thickness in mm. Absent or <= 0 falls back to the backend's default. */
  layerHeight: 'data-stl-layer-height',
  /** Marks an SVG element as the projection of a backend-handled 3D object. Value is always '1'. */
  marker: 'data-stl',
  /**
   * The 3D object's transform: a column-major 4x4 matrix, 16 numbers separated by spaces.
   *
   * Maps the mesh from its own space (STL files are in mm) into scene space (0.1mm, matching
   * `constant.dpmm`), so the mm -> 0.1mm factor of 10 is already baked in. Consumers apply the
   * matrix as-is and never need to reason about units.
   */
  matrix: 'data-stl-matrix',
  /** `'dot'` or `'line'`. Absent means line. */
  mode: 'data-stl-mode',
  /** Distance between dots in mm, dot mode only. Absent or <= 0 falls back to the backend's default. */
  pointSpacing: 'data-stl-point-spacing',
  /** Editable SVG source for an extrusion generated by Beam Studio. Imported STL files omit it. */
  source: 'data-stl-source',
  /**
   * The decomposed transform as JSON — **frontend only**, the backend uses `matrix`.
   *
   * The matrix alone cannot be turned back into position / rotation / scale / flip (a mirror makes
   * the decomposition ambiguous), so reopening a file would lose which axis was flipped and land the
   * rotation somewhere else. This carries the stored form, plus the transform the object was
   * imported with, which the reset buttons need.
   */
  transform: 'data-stl-transform',
} as const;

/** Metadata for a zero-thickness textured plane. */
export const PHOTO_3D_ATTR = {
  /** Original plane height in millimetres, before the object's transform is applied. */
  height: 'data-stl-photo-height',
  /** Marks an SVG image as a 3D photo plane. Export adds `data-stl-kind="photo"` temporarily. */
  marker: 'data-stl-photo',
  /** Original plane width in millimetres, before the object's transform is applied. */
  width: 'data-stl-photo-width',
} as const;

/** Frontend and .beam metadata for a relief point cloud generated from a photo. */
export const POINT_CLOUD_ATTR = {
  /**
   * Marks a photo whose 3D representation is a point cloud rather than its fallback plane.
   * The value is the binary format version, so an SVG-only reader can reject a mismatched block.
   */
  marker: 'data-stl-point-cloud',
} as const;
