/**
 * Attributes on a 3D object's SVG projection. Everything Swiftray needs to place the geometry
 * travels on these because the projection ends up in both the exported SVG and the .beam file.
 *
 * The 3D object owns its geometry and transform. Its SVG rect/image is only a derived projection;
 * controls update the 3D object and regenerate it. The element id links both sides and keys binary
 * payloads. Infill uses the projection's regular SVG `fill`, not a separate 3D attribute.
 */
export const STL_ATTR = {
  /** Backend geometry: absent means STL mesh; `photo` uses image pixels; `point-cloud` selects BSPC. */
  kind: 'data-stl-kind',
  /** Slice thickness in mm. Absent or <= 0 falls back to the backend's default. */
  layerHeight: 'data-stl-layer-height',
  /** Marks an SVG element as the projection of a backend-handled 3D object. Value is always '1'. */
  marker: 'data-stl',
  /** Column-major 4x4 transform into 0.1 mm scene units, including the mm-to-scene factor. */
  matrix: 'data-stl-matrix',
  /** Minimum slice thickness in mm. A positive value opts line mode into adaptive slicing. */
  minLayerHeight: 'data-stl-min-layer-height',
  /** `'dot'` or `'line'`. Absent means line. */
  mode: 'data-stl-mode',
  /** Distance between dots in mm, dot mode only. Absent or <= 0 falls back to the backend's default. */
  pointSpacing: 'data-stl-point-spacing',
  /** Editable SVG source for an extrusion generated by Beam Studio. Imported STL files omit it. */
  source: 'data-stl-source',
  /** Frontend-only decomposed current/import transform; the backend uses `matrix`. */
  transform: 'data-stl-transform',
} as const;

/** Metadata for a zero-thickness textured plane. */
export const PHOTO_3D_ATTR = {
  /** Original plane height in millimetres, before the object's transform is applied. */
  height: 'data-stl-photo-height',
  /** Marks an SVG image as a 3D photo plane. Export adds `data-stl-kind="photo"` temporarily. */
  marker: 'data-stl-photo',
  /** Original plane width in millimetres, before the object's transform is applied. */
  width: 'data-stl-photo-width',
} as const;

/** Frontend and .beam metadata for a generated or directly imported point cloud. */
export const POINT_CLOUD_ATTR = {
  /**
   * Marks a projection whose 3D representation lives in the BSPC block. The value is the binary
   * format version, so an SVG-only reader can reject a mismatched block.
   */
  marker: 'data-stl-point-cloud',
} as const;
