module.exports = {
    NOTIFY_LANGUAGE         : 'NOTIFY_LANGUAGE',
    NOTIFY_MACHINE_STATUS   : 'NOTIFY_MACHINE_STATUS',

    FRONTEND_READY          : 'FRONTEND_READY',
    BACKEND_UP              : 'BACKEND_UP',
    BACKEND_DOWN            : 'BACKEND_DOWN',
    CHECK_BACKEND_STATUS    : 'CHECK_BACKEND_STATUS',
    NOTIFY_BACKEND_STATUS   : 'NOTIFY_BACKEND_STATUS',

    MENU_CLICK              : 'MENU_CLICK',
    UPDATE_CUSTOM_TITLEBAR  : 'UPDATE_CUSTOM_TITLEBAR',
    DISABLE_MENU_ITEM       : 'DISABLE_MENU_ITEM',
    ENABLE_MENU_ITEM        : 'ENABLE_MENU_ITEM',

    POPUP_MENU              : 'POPUP_MENU_ITEM',

    UPDATE_ACCOUNT          : 'UPDATE_ACCOUNT',

    GET_AVAILABLE_FONTS     : 'GET_AVAILABLE_FONTS',
    FIND_FONTS              : 'FIND_FONTS',
    FIND_FONT               : 'FIND_FONT',
    REQUEST_PATH_D_OF_TEXT  : 'REQUEST_PATH_D_OF_TEXT',
    RESOLVE_PATH_D_OF_TEXT  : 'RESOLVE_PATH_D_OF_TEXT',

    SET_AS_DEFAULT          : 'SET_AS_DEFAULT',

    CHECK_FOR_UPDATE        : 'CHECK_FOR_UPDATE',
    UPDATE_AVAILABLE        : 'UPDATE_AVAILABLE',
    DOWNLOAD_UPDATE         : 'DOWNLOAD_UPDATE',
    DOWNLOAD_PROGRESS       : 'DOWNLOAD_PROGRESS',
    UPDATE_DOWNLOADED       : 'UPDATE_DOWNLOADED',
    QUIT_AND_INSTALL        : 'QUIT_AND_INSTALL',

    SVG_URL_TO_IMG_URL      : 'SVG_URL_TO_IMG_URL',
    SVG_URL_TO_IMG_URL_DONE : 'SVG_URL_TO_IMG_URL_DONE'
};
