import { LayerModule } from '@core/app/constants/layer-module/layer-modules';
import layerManager from '@core/app/svgedit/layer/layerManager';
import { getData } from '@core/helpers/layer/layer-config-helper';

import { PRINT_AND_CUT_LAYER_ATTR } from '../constants';

/**
 * Cutting layer groups generated by a previous run, under `root` (the live
 * document by default, or a preview clone).
 */
export const getGeneratedCutLayers = (root: Document | Element = document): SVGGElement[] => [
  ...root.querySelectorAll<SVGGElement>(`g.layer[${PRINT_AND_CUT_LAYER_ATTR}]`),
];

/**
 * Visible UV Print layer groups holding the user's design: only UV Print
 * layers are printed, so only they count as design content. A cutting layer
 * generated by a previous run is output, not design content, and is never
 * included: tracing it would offset the new cut path from the old cut line,
 * and printing it would put cut lines on the sheet.
 * @param exclude - extra layer to leave out (the cut layer picked in layer mode)
 */
export const getContentsLayers = (exclude?: null | SVGGElement): SVGGElement[] =>
  layerManager
    .getAllLayers()
    .map((layer) => layer.getGroup())
    .filter(
      (group) =>
        group.getAttribute('display') !== 'none' &&
        group !== exclude &&
        !group.hasAttribute(PRINT_AND_CUT_LAYER_ATTR) &&
        getData(group, 'module') === LayerModule.UV_PRINT,
    );
