name: beam-studio-ci

on: [pull_request]

jobs:
  unit-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node-version: [12.19]
        python-version: [3.7]
        os: [macOS-latest, windows-latest]
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: yarn install
      - name: Run unit tests
        run: yarn run spec
  # https://github.com/marketplace/actions/eslint-plus
  eslint-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: bradennapier/eslint-plus-action@v3.4.2
        with:
          npmInstall: true
          issueSummaryOnlyOnEvent: true


