name: beam-studio-ci

on: [pull_request]

jobs:
  # https://github.com/marketplace/actions/run-eslint-with-reviewdog
  eslint-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Eslint check
        uses: reviewdog/action-eslint@v1
        # with:
        # remove this parameter due to this known issue: https://github.com/reviewdog/reviewdog/issues/848
        #   fail_on_error: true
