name: Electron CD Linux

on:
  push:
    tags:
      - '*'

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node-version: [12.19]
        python-version: [3.7]
        os: [ubuntu-16.04, ubuntu-18.04]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}

      - name: Set up Node ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          sudo apt-get install -y python3-setuptools
      - name: Setup gcc
        if: matrix.os == 'ubuntu-16.04'
        run: |
          sudo apt-get update
          sudo apt-get install gcc-7
          sudo apt-get install g++-7
          sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-7 70 --slave /usr/bin/g++ g++ /usr/bin/g++-7
          gcc -v
          g++ -v

      - name: Checkout Beamify
        uses: actions/checkout@v2
        with:
          repository: flux3dp/beamify
          ref: master
          token: ${{ secrets.REPO_TOKEN }}
          path: .github/actions/beamify

      - name: Install Beamify
        uses: ./.github/actions/beamify

      - name: Install Fluxsvg
        uses: flux3dp/fluxsvg@master

      - name: Checkout FluxClient
        uses: actions/checkout@v2
        with:
          repository: flux3dp/fluxclient-dev
          ref: develop
          token: ${{ secrets.REPO_TOKEN }}
          path: .github/actions/fluxclient

      - name: Install FluxClient
        uses: ./.github/actions/fluxclient

      - name: Build Flux Api
        uses: flux3dp/fluxghost@develop
        env:
          LC_ALL: en_US.UTF-8
          LC_CTYPE: en_US.UTF-8

      - name: Checkout Beam Studio Core
        uses: actions/checkout@v2
        with:
          repository: flux3dp/beam-studio-core
          ref: "1.9.4"
          token: ${{ secrets.REPO_TOKEN }}
          path: .github/actions/beam-studio-core

      - name: Copy Beam Studio Core
        run: |
          cp -R .github/actions/beam-studio-core ../beam-studio-core

      - name: Build Beam Studio
        run: |
          echo $PUBLISH_PATH
          mkdir backend

          yarn install
          webpack

          cp -R $HOME/flux_api_swap backend/flux_api
          ./backend/flux_api/flux_api --test --without_pcl

          sudo bash ./build/clearup-develop-files.sh

          if [ ${{ matrix.os }} = "ubuntu-16.04" ]
          then
            export PUBLISH_PATH=""
          else
            export PUBLISH_PATH="-18.04"
          fi
          echo $PUBLISH_PATH

          yarn dist --publish always
        env:
          PUBLISH_BUCKET: beamstudio
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Cleanup artifacts
        run: |
          mkdir artifacts
          mv dist/*.deb artifacts

      - name: Upload artifacts
        uses: actions/upload-artifact@v1
        with:
          name: ${{matrix.os}}
          path: artifacts
