name: global ci

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  actions: read
  contents: read

jobs:
  unit-test-and-lint:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [22]
        python-version: [3.8]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Setup Pnpm
        uses: pnpm/action-setup@v4
        with:
          run_install: false

      - name: Setup Node ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-setuptools libfontconfig1-dev

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ./apps/app/requirements.txt

      - run: pnpm -r install

      - uses: nrwl/nx-set-shas@v4
        with:
          main-branch-name: main
      - run: pnpm nx affected -t test lint --output-style static --ci
