name: global ci

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  actions: read
  contents: read

jobs:
  unit-test-and-lint:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [24]
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Setup Pnpm
        uses: pnpm/action-setup@v6
        with:
          run_install: false

      - name: Setup Node ${{ matrix.node-version }}
        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"

      - name: Install system dependencies
        timeout-minutes: 5
        run: |
          sudo apt-get update -o Acquire::Retries=2 -o Acquire::http::Timeout=15
          sudo apt-get install -y --no-install-recommends libfontconfig1-dev

      - run: pnpm -r install

      - uses: nrwl/nx-set-shas@v5
        with:
          main-branch-name: main
      - run: pnpm nx affected -t test lint --output-style static --ci
